---
# This is a test container and is not intended for production use.
# The passwords are public here to make the setup transparent.
user_setup_password_ansible: "ansible"
user_setup_password_salt_ansible: "pUxp88aAfO1U7G7q"
user_setup_users:
  - name: "ansible"
    state: present
    uid: 1001
    shell: "/bin/bash"
    create_home: true
    groups: []
    groups_append: true
    password: "{{ user_setup_password_ansible | password_hash('sha512', user_setup_password_salt_ansible) }}"
    sudo_access: true
    sudo_nopasswd: false
    env_var_setup: false
    env_var_file: ".env_vars"
    user_directories: []
    ssh_directory: ".ssh"
    ssh_authorized_keys_exclusive: true
    ssh_authorized_keys: []
